services:
  - type: web
    name: bot-whatsapp
    env: node
    buildCommand: npm install --ignore-scripts
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true